name: GitHub Workflow
on:
  push:
    branches:
      - main
jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
      - name: Build with Maven
        working-directory: backend/warptracker
        run: ./mvnw --batch-mode --update-snapshots package